export const FETCH_IMAGE_REQUEST = "FETCH_IMAGE_REQUEST";
export const FETCH_IMAGE_SUCCESS = "FETCH_IMAGE_SUCCESS";
export const FETCH_IMAGE_FAILURE = "FETCH_IMAGE_FAILURE";
export const FETCH_SINGLE_IMAGE_REQUEST = "FETCH_SINGLE_IMAGE_REQUEST";
export const FETCH_SINGLE_IMAGE_SUCCESS = "FETCH_SINGLE_IMAGE_SUCCESS";
export const FETCH_SINGLE_IMAGE_FAILURE = "FETCH_SINGLE_IMAGE_FAILURE";

